export default {
  defaultPersonalTab: [
    { _type: 'StatisticsWidgetLiteImpl', templateId: 'overview.kpi.case.total', widgetType: 'KPI', order: 0, size: 0, x: 0, y: 0, w: 1, h: 1, i: 'page-0-widget-0', componentType: 'kpi', widgetTitle: '', componentId: 'KpiWidget', dataParams: { durUnit: 'month', durValue: 1 }, kpiFormat: 'number', kpiId: 'OverviewCase', moved: false },
    { _type: 'StatisticsWidgetLiteImpl', templateId: 'overview.kpi.event.total', widgetType: 'KPI', order: 0, size: 0, x: 1, y: 0, w: 1, h: 1, i: 'page-0-widget-1', componentType: 'kpi', widgetTitle: '', componentId: 'KpiWidget', dataParams: { durUnit: 'month', durValue: 1 }, kpiFormat: 'number', kpiId: 'OverviewEvent', moved: false },
    { _type: 'StatisticsWidgetLiteImpl', templateId: 'overview.kpi.start.timestamp', widgetType: 'KPI', order: 0, size: 0, x: 2, y: 0, w: 1, h: 1, i: 'page-0-widget-2', componentType: 'kpi', widgetTitle: '', componentId: 'KpiWidget', dataParams: {}, kpiFormat: 'string', kpiId: 'OverviewStartTime', moved: false },
    { _type: 'StatisticsWidgetLiteImpl', templateId: 'overview.kpi.end.timestamp', widgetType: 'KPI', order: 0, size: 0, x: 3, y: 0, w: 1, h: 1, i: 'page-0-widget-3', componentType: 'kpi', widgetTitle: '', componentId: 'KpiWidget', dataParams: {}, kpiFormat: 'string', kpiId: 'OverviewEndTime', moved: false },
    { _type: 'StatisticsWidgetLiteImpl', templateId: 'overview.kpi.completion.rate', widgetType: 'KPI', order: 0, size: 0, x: 4, y: 0, w: 1, h: 1, i: 'page-0-widget-4', componentType: 'kpi', widgetTitle: '', componentId: 'KpiWidget', dataParams: {}, kpiFormat: 'percentage', kpiId: 'OverviewCompleteRatio', moved: false },
    { _type: 'StatisticsWidgetLiteImpl', templateId: 'activity.kpi.total', widgetType: 'KPI', order: 0, size: 0, x: 5, y: 0, w: 1, h: 1, i: 'page-0-widget-5', componentType: 'kpi', widgetTitle: '', componentId: 'KpiWidget', dataParams: {}, kpiFormat: 'number', kpiId: 'ActivityCount', moved: false },
    { _type: 'StatisticsWidgetLiteImpl', templateId: 'general.kpi.case.duration.over.ref.model', widgetType: 'KPI', order: 0, size: 0, x: 6, y: 0, w: 1, h: 1, i: 'page-0-widget-6', componentType: 'kpi', widgetTitle: '', componentId: 'KpiWidget', dataParams: {}, kpiFormat: 'custom', kpiId: 'TimeoutCase', moved: false },
    { _type: 'StatisticsWidgetLiteImpl', templateId: 'general.kpi.case.outlier', widgetType: 'KPI', order: 0, size: 0, x: 7, y: 0, w: 1, h: 1, i: 'page-0-widget-7', componentType: 'kpi', widgetTitle: '', componentId: 'KpiWidget', dataParams: { ucl: 0.9, threshold: 'ucl' }, kpiFormat: 'custom', kpiId: 'CaseTimeOutlier', moved: false },
    { _type: 'StatisticsWidgetLiteImpl', templateId: 'overview.chart.duration.by.case', widgetType: 'BAR_CHART', order: 0, size: 0, x: 0, y: 1, w: 4, h: 3, i: 'page-0-widget-8', componentType: 'chart', widgetTitle: '', componentId: 'CaseDurationHistogram', dataParams: {}, colorPalette: true, colorTheme: 3, moved: false },
    { _type: 'StatisticsWidgetLiteImpl', templateId: 'overview.chart.case.duration', widgetType: 'BAR_CHART', order: 0, size: 0, x: 0, y: 4, w: 8, h: 3, i: 'page-0-widget-9', componentType: 'chart', widgetTitle: '', componentId: 'CaseSectionDuration', dataParams: {}, moved: false },
    { _type: 'StatisticsWidgetLiteImpl', templateId: 'activity.chart.mean.duration', widgetType: 'BAR_CHART', order: 0, size: 0, x: 4, y: 1, w: 4, h: 3, i: 'page-0-widget-10', componentType: 'chart', widgetTitle: '', componentId: 'ActivityDuration', dataParams: {}, moved: false }
  ],
  selectedTab: ''
};
